export default {
  logo: require("@/assets/images/logo.png"),
  dd: require("@/assets/images/DD.png"),
  verify: require("@/assets/images/verify-Mark.png"),
  home: require("@/assets/icons/home.png"),
  homeRed: require("@/assets/icons/home-r.png"),
  search: require("@/assets/icons/search.png"),
  chat: require("@/assets/icons/chat.png"),
  chatRed: require("@/assets/icons/chat-r.png"),
  calendar: require("@/assets/icons/calender.png"),
  profile: require("@/assets/icons/profile.png"),
  profileRed: require("@/assets/icons/profile-r.png"),
  Google: require("@/assets/SocialIcons/google.png"),
  facebook: require("@/assets/SocialIcons/facebook.png"),
  Consultant: require("@/assets/images/Consultant.png"),
  Candidate: require("@/assets/images/Candidate.png"),
  Lawyer: require("@/assets/images/Lawyer.png"),
  Arrow: require("@/assets/images/Arrow.png"),
  user: require("@/assets/images/user.png"),
  filter: require("@/assets/images/filter.png"),
  Message: require("@/assets/images/Message.png"),
  Flag: require("@/assets/images/flag.png"),
  leftArrow: require("@/assets/images/leftArrow.png"),
};
